CREATE TABLE mot_alea (
    id INT PRIMARY KEY,
    mot TEXT NOT NULL
);

INSERT INTO mot_alea (id, mot) VALUES
(1, 'chat'),
(2, 'chien'),
(3, 'oiseau'),
(4, 'python'),
(5, 'docker'),
(6, 'flask'),
(7, 'postgres'),
(8, 'linux'),
(9, 'serveur'),
(10, 'reseau'),
(11, 'cloud'),
(12, 'api'),
(13, 'http'),
(14, 'json'),
(15, 'sql'),
(16, 'html'),
(17, 'css'),
(18, 'javascript'),
(19, 'react'),
(20, 'node'),
(21, 'nginx'),
(22, 'proxy'),
(23, 'tcp'),
(24, 'udp'),
(25, 'socket'),
(26, 'thread'),
(27, 'process'),
(28, 'kernel'),
(29, 'bash'),
(30, 'shell'),
(31, 'git'),
(32, 'github'),
(33, 'ci'),
(34, 'cd'),
(35, 'devops'),
(36, 'kubernetes'),
(37, 'helm'),
(38, 'terraform'),
(39, 'ansible'),
(40, 'virtualisation'),
(41, 'vm'),
(42, 'conteneur');
